// Code generated by mockery v2.29.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/yaraya24/book-meeting-room/internal/domain"

	time "time"
)

// AvailableRoomsRepo is an autogenerated mock type for the AvailableRoomsRepo type
type AvailableRoomsRepo struct {
	mock.Mock
}

// FindRooms provides a mock function with given fields: ctx, date
func (_m *AvailableRoomsRepo) FindRooms(ctx context.Context, date time.Time) ([]domain.Room, error) {
	ret := _m.Called(ctx, date)

	var r0 []domain.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) ([]domain.Room, error)); ok {
		return rf(ctx, date)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) []domain.Room); ok {
		r0 = rf(ctx, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewAvailableRoomsRepo interface {
	mock.TestingT
	Cleanup(func())
}

// NewAvailableRoomsRepo creates a new instance of AvailableRoomsRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAvailableRoomsRepo(t mockConstructorTestingTNewAvailableRoomsRepo) *AvailableRoomsRepo {
	mock := &AvailableRoomsRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
