// Code generated by mockery v2.29.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// BookRoomRepo is an autogenerated mock type for the BookRoomRepo type
type BookRoomRepo struct {
	mock.Mock
}

// BookRoom provides a mock function with given fields: ctx, room, user, date
func (_m *BookRoomRepo) BookRoom(ctx context.Context, room string, user int, date time.Time) error {
	ret := _m.Called(ctx, room, user, date)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, time.Time) error); ok {
		r0 = rf(ctx, room, user, date)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewBookRoomRepo interface {
	mock.TestingT
	Cleanup(func())
}

// NewBookRoomRepo creates a new instance of BookRoomRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewBookRoomRepo(t mockConstructorTestingTNewBookRoomRepo) *BookRoomRepo {
	mock := &BookRoomRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
