// Code generated by mockery v2.29.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// RoomExistsChecker is an autogenerated mock type for the RoomExistsChecker type
type RoomExistsChecker struct {
	mock.Mock
}

// RoomExists provides a mock function with given fields: ctx, room
func (_m *RoomExistsChecker) RoomExists(ctx context.Context, room string) (bool, error) {
	ret := _m.Called(ctx, room)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, room)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, room)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, room)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewRoomExistsChecker interface {
	mock.TestingT
	Cleanup(func())
}

// NewRoomExistsChecker creates a new instance of RoomExistsChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRoomExistsChecker(t mockConstructorTestingTNewRoomExistsChecker) *RoomExistsChecker {
	mock := &RoomExistsChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
