// Code generated by mockery v2.29.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/yaraya24/book-meeting-room/internal/domain"
)

// AuthenticationRepo is an autogenerated mock type for the AuthenticationRepo type
type AuthenticationRepo struct {
	mock.Mock
}

// FindUser provides a mock function with given fields: ctx, username
func (_m *AuthenticationRepo) FindUser(ctx context.Context, username string) (domain.User, error) {
	ret := _m.Called(ctx, username)

	var r0 domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.User, error)); ok {
		return rf(ctx, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.User); ok {
		r0 = rf(ctx, username)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewAuthenticationRepo interface {
	mock.TestingT
	Cleanup(func())
}

// NewAuthenticationRepo creates a new instance of AuthenticationRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAuthenticationRepo(t mockConstructorTestingTNewAuthenticationRepo) *AuthenticationRepo {
	mock := &AuthenticationRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
