// Code generated by mockery v2.29.0. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// RoomBooker is an autogenerated mock type for the RoomBooker type
type RoomBooker struct {
	mock.Mock
}

// BookAvailableRoom provides a mock function with given fields: ctx, room, user, date
func (_m *RoomBooker) BookAvailableRoom(ctx context.Context, room string, user int, date time.Time) error {
	ret := _m.Called(ctx, room, user, date)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, time.Time) error); ok {
		r0 = rf(ctx, room, user, date)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewRoomBooker interface {
	mock.TestingT
	Cleanup(func())
}

// NewRoomBooker creates a new instance of RoomBooker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRoomBooker(t mockConstructorTestingTNewRoomBooker) *RoomBooker {
	mock := &RoomBooker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
